<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>922311e1-d534-43d7-ad97-8efb9918420e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspireStorage.ApiService\AspireStorage.ApiService.csproj" />
    <ProjectReference Include="..\AspireStorage.Web\AspireStorage.Web.csproj" />
      <ProjectReference Include="..\AspireStorage.WorkerService\AspireStorage.WorkerService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.2.1" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" Version="9.2.1" />
  </ItemGroup>

</Project>
